version: "3"
services:
  codename_api:
    image: node:alpine3.17
    volumes:
      - ./api:/code
    environment:
      - NODE_ENV=development
    working_dir: /code
    #command: "npm run start:dev"
    command: sh -c "npm i && npm run start:dev"
    ports:
      - 9123:8555 # NestJS Port
      - 9124:8777 # Prisma Studio Port
    depends_on:
      - codename_db
    links:
      - codename_db
    container_name: codename_api

  codename_db:
    image: leyume/mariadb
    volumes:
      - "./db/mysql:/var/lib/mysql:rw"
      - "./db/my.cnf:/etc/mysql/my.cnf"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  codename_adminer:
    image: leyume/adminer:mysql
    restart: always
    ports:
      - 9125:80
    depends_on:
      - codename_db
    links:
      - codename_db
