name: Deploy
on:
  push:
    branches: [main]

  # Run workflow manually
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Moving files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CODENAME_HOST }}
          username: ${{ secrets.CODENAME_USER }}
          password: ${{ secrets.CODENAME_PASS }}
          port: ${{ secrets.CODENAME_PORT }}
          source: "*"
          target: ${{ secrets.CODENAME_TARGET }}
